stripetest/core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path("", ItemListView.as_view(), name="index"),
    path("item/<int:pk>/", ItemDetailView.as_view(), name="detail"),
    path("success/", success, name="success"),
    path("cancel/", cancel, name="cancel"),
    path("buy/<int:pk>/", CreateCheckoutSession.as_view(), name="create-checkout-single"),
    path("buy/", CreateCheckoutSession.as_view(), name="create-checkout-cart"),
    path("order/<int:pk>/", OrderView.as_view(), name="order_post"),
    path("order/", OrderView.as_view(), name="order_get"),
    path("delete/<int:pk>/", delete_item, name="delete_item"),

]

stripetest/stripetest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls"))
]

stripetest/core/models.py
from django.db import models
from django.contrib.auth. models import AbstractUser

class AnonymousUser(models.Model):
    user_id = models.CharField(max_length=255, unique=True)

class Discount(models.Model):
    amount = models.IntegerField()

    def __str__(self):
        return f"{self.amount}"


class Tax(models.Model):
    amount = models.IntegerField()
    
    def __str__(self):
        return f"{self.amount}"

class Item(models.Model):
    class Currency(models.TextChoices):
        DOLLAR = "usd", "Dollar"
        ROUBLE = "rub", "Rouble"
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField(default=0)
    currency = models.CharField(max_length=10, choices=Currency.choices, default=Currency.DOLLAR)


    
    @property
    def price_display_dollar(self):
        return "{:,}$".format(self.price).replace(",", ".")
    
    @property
    def price_display_rouble(self):
        return "{:,}₽".format(self.price).replace(",", ".")
    
    def __str__(self):
        if self.currency == self.Currency.DOLLAR:
            return f"{self.name}/{self.price_display_dollar}"
        if self.currency == self.Currency.ROUBLE:
            return f"{self.name}/{self.price_display_rouble}"

class Order(models.Model):
    items = models.ManyToManyField(Item)
    user = models.ForeignKey(AnonymousUser, on_delete=models.CASCADE, related_name="orders")
    tax = models.ForeignKey(Tax, on_delete=models.SET_DEFAULT, default=1)
    discount = models.ForeignKey(Discount, on_delete=models.SET_DEFAULT, default=1)

stripetest/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseNotFound
from django.views.generic import ListView, DetailView
from django.views import View
from core.models import *
from django.urls import reverse
from django.contrib import messages
import stripe
import uuid
from django.conf import settings


DOLLAR = stripe.api_key = settings.STRIPE_SECRET_KEY_DOLLAR
ROUBLE = stripe.api_key = settings.STRIPE_SECRET_KEY_ROUBLE


DOMAIN = "http://127.0.0.1:8000"

class OrderView(View):
    def post(self, request, *args, **kwargs):
        item_id = self.kwargs["pk"]
        item = Item.objects.get(pk=item_id)
        if "user_id" not in request.session:
            request.session["user_id"] = str(uuid.uuid4())
        user_id = request.session["user_id"]
        user, _ = AnonymousUser.objects.get_or_create(user_id = user_id)
        order, _ = Order.objects.get_or_create(user = user)
        order.items.add(item)
        i_order = Order.objects.filter(pk=order.id)
        i_order.update(tax = 2, discount = 2)
        messages.success(request, "Товар добавлен в корзину." )
        return redirect(f"core:detail", pk=item_id)

    def get(self, request, *args, **kwargs):
        if "user_id" not in request.session:
            request.session["user_id"] = str(uuid.uuid4())
        user_id = request.session["user_id"]
        user, _ = AnonymousUser.objects.get_or_create(user_id=user_id)
        order = Order.objects.filter(user=user).first()
        # Конечная сумма в корзине всегда в долларах
        end_sum = 0
        if order:
            for item in order.items.all():
                if item.currency == Item.Currency.DOLLAR:
                    end_sum += item.price 
                if item.currency == Item.Currency.ROUBLE:
                    end_sum += (item.price / 100)
            end_sum
        return render(request, "core/order.html", {"order":order, "end_sum":end_sum, "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY_DOLLAR})
        
class CreateCheckoutSession(View):
    
    def get(self, request, *args, **kwargs):
        item_id = self.kwargs["pk"]
        item = Item.objects.get(pk = item_id)
        item_price = item.price
        item_currency = item.currency
        
        if item_currency == "rub":
            stripe.api_key = settings.STRIPE_SECRET_KEY_ROUBLE
        elif item_currency == "usd":
            stripe.api_key = settings.STRIPE_SECRET_KEY_DOLLAR

        if item_currency == "usd":
            item_price *= 100

        elif item_currency == "rub":
            item_price *= 100
        
        intent = stripe.PaymentIntent.create(
            automatic_payment_methods={"enabled": True},
            amount = item_price,
            currency = item_currency,
            metadata={
                "product_id": item.id
            }
        )
        return JsonResponse({"client_secret":intent.client_secret}) # Так как в бонусных заданиях было указано использовать Payment Intent приходится возвращать именно это
    
    def post(self, request, *args, **kwargs):
        user_id = request.session["user_id"]
        user = get_object_or_404(AnonymousUser, user_id=user_id)
        order = Order.objects.filter(user=user).first()
        tax = order.tax.amount
        discount = order.discount.amount

        metadata = {}
        amount = 0

        for idx, item in enumerate(order.items.all()):
            if item.currency == Item.Currency.DOLLAR:
                amount += int(item.price * 100)
            elif item.currency == Item.Currency.ROUBLE:
                amount += int(item.price)
            metadata[f"item_{idx}_id"] = str(item.id)

        tax_amount = (tax / 100) * amount
        discount_amount = (discount / 100) * amount
        final_amount = (amount + tax_amount) - discount_amount

        stripe.api_key = settings.STRIPE_SECRET_KEY_DOLLAR
        intent = stripe.PaymentIntent.create(
            automatic_payment_methods={"enabled": True},
            metadata = metadata,
            amount = int(final_amount),
            currency = "usd"
        )
        return JsonResponse({"client_secret":intent.client_secret}) # Так как в бонусных заданиях было указано использовать Payment Intent приходится возвращать именно это



class ItemDetailView(DetailView):
    template_name = "core/detailed.html"
    model = Item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = self.get_object()

        if item.currency == Item.Currency.DOLLAR:
            context["stripe_public_key"] = settings.STRIPE_PUBLIC_KEY_DOLLAR
        elif item.currency == Item.Currency.ROUBLE:
            context["stripe_public_key"] = settings.STRIPE_PUBLIC_KEY_ROUBLE

        return context
    
class ItemListView(ListView):
    queryset = Item.objects.all()
    context_object_name = "items"
    paginate_by = 3
    template_name = "core/index.html"

def delete_item(request, pk):
    user_id = request.session["user_id"]
    user = get_object_or_404(AnonymousUser, user_id=user_id)
    order = Order.objects.filter(user = user).first()
    if order:
        order.items.remove(pk)
    return redirect("/order/")

def success(request):
    return HttpResponse(200)

def cancel(request):
    return HttpResponseBadRequest(400)

stripetest/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/style.css' %}">
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'includes/messages.html' %}
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'core:index' %}">Главная</a></li>
                <li><a href="{% url 'core:order_get' %}">Корзина</a></li>
            </ul>
        </nav>
    </header>
    {% block content %}

    {% endblock %}
</body>
</html>

stripetest/templates/core/detailed.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ object.title }}{% endblock %}

{% block content %}

    <div class="container">

        <a href="{% url 'core:index' %}">Назад</a>
        <h1>{{ object.name }}</h1>
        {% if object.currency == "usd" %}
            <p>{{ object.price_display_dollar }}</p>
        {% elif object.currency == "rub" %}
            <p>{{ object.price_display_rouble }}</p>
        {% endif %}
        <p>{{ object.description }}</p>
        <form action="{% url 'core:order_post' object.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Добавить в корзину</button>
        </form>

        <form id="payment-form">
            <div id="card-element"><!-- Элемент Stripe Elements --></div>
                <button type="button" id="checkout-button">Купить</button>
            <div id="error-message"></div>
        </form>
        {% csrf_token %}
    </div>
<script>
var stripe = Stripe("{{ stripe_public_key }}");
var elements = stripe.elements();
var cardElement = elements.create('card');
cardElement.mount('#card-element');

var checkoutButton = document.getElementById("checkout-button");
var errorMessage = document.getElementById("error-message");

checkoutButton.addEventListener("click", function () {
  fetch("{% url 'core:create-checkout-single' object.id %}")  
    .then(response => response.json())
    .then(data => {
      stripe.confirmCardPayment(data.client_secret, {
        payment_method: {
          card: cardElement,
        }
      }).then(function(result) {
        if (result.error) {
          errorMessage.textContent = result.error.message;
        } else if (result.paymentIntent.status === 'succeeded') {
          window.location.href = "/success/";
        }
      });
    })
    .catch(error => console.error("Произошла ошибка при создании платежа.", error));
});
</script>
{% endblock %}

stripetest/templates/core/index.html
{% extends "base.html" %}
{% block title %}Главная{% endblock %}

{% block content %}
    <div class="container">
        <h1>Товары</h1>
        <ul>
        {% for item in items %}
            <li><a href="{% url 'core:detail' item.pk %}">{{ item.name }}</a></li>
            {% empty %}
            <p>Товаров нет.</p>
        {% endfor %}
        </ul>

        {% include 'pagination.html' with page=page_obj %}
    </div>


{% endblock %}

stripetest/templates/core/order.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    <div class="container">
        <h1>Заказ</h1>
        <h2>Конечная сумма считается в долларах</h2>
        
        {% if order %}
        <ul>
            {% for item in order.items.all %}
                <li>
                    <a href="{% url 'core:detail' item.id %}">{{ item.name }}</a> 
                    {% if item.currency == "usd" %}
                        <p>{{ item.price_display_dollar }}</p>

                    {% elif item.currency == "rub" %}
                        <p>{{ item.price_display_rouble }}</p>
                    {% endif %}
                    <form action="{% url 'core:delete_item' item.id %}" method="post">
                        <button>Удалить</button>
                        {% csrf_token %}
                    </form>
                </li>
                <hr>
            {% empty %}
                <p>В корзине нет товаров</p>
            {% endfor %}
        </ul>
        
        <p>Сумма: {{ end_sum }} $</p>
        
        <form id="payment-form">
            <div id="card-element"><!-- Элемент Stripe Elements --></div>
                <button type="button" id="checkout-button">Купить</button>
            <div id="error-message"></div>
        </form>
        
            {% csrf_token %}
        {% else %}
            <p>Нет корзины</p>
        {% endif %}
    </div>

<script>
var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
var elements = stripe.elements();
var checkoutButton = document.getElementById("checkout-button");
var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
var cardElement = elements.create('card');
cardElement.mount('#card-element');

checkoutButton.addEventListener("click", function () {
  fetch("{% url 'core:create-checkout-cart' %}", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-CSRFToken": csrftoken,
    }
  })
  .then(response => response.json())
  .then(data => {
    console.log("Client secret:", data.client_secret);
    stripe.confirmCardPayment(data.client_secret, {
        payment_method: {
          card: cardElement,
        }
      }).then(function(result) {
      if (result.error) {
        alert("Ошибка оплаты: " + result.error.message);
      } else if (result.paymentIntent.status === 'succeeded') {
        window.location.href = "/success/";
      }
    });
  })
  .catch(error => {
    console.error("Error:", error);
    alert("Произошла ошибка при создании платежа." , error);
  });
});

</script>

{% endblock %}

stripetest/templates/includes/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    
    <script>
        {% if message.tags %}
        alert("{{ message }}")
        {% endif %}
    </script>
    {% endfor %}
</ul>
{% endif %}

stripetest/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
        {% endif %}
        <span class="current">
            Страница {{ page.number }} из {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Следующая</a>
        {% endif %}
    </span>
</div>